
export interface Event {
  title: string;
  club: string;
  description: string;
  longDescription: string;
  registrationLink?: string;
  eventType?: string;
  targetAudience?: string;
  participants?: string;
  duration?: string;
  venue?: string;
  date?: string;
  timing?: string;
  fees?: string;
  prizes?: string;
  requirements?: {
    technical?: string[];
    resources?: string[];
    special?: string;
  };
  volunteers?: string;
  contactName?: string;
  contactDetails?: string;
  facultyCoordinator?: string;
  facultyContact?: string;
  category: 'technical' | 'non-technical' | 'special-events';
}

export const eventsData: Event[] = [
  // ================== Technical Events ==================
  {
    title: 'PROJECT EXPO',
    club: 'Raghu Scope',
    description: 'An open-domain project showcase for innovations in IoT, AI, robotics, and more. Teams of up to 4 members.',
    longDescription: 'The Project Expo is an open-domain platform for students to showcase their innovative projects in fields like IoT, AI, robotics, software applications, and more. A great opportunity to get feedback and recognition for your hard work.',
    fees: '₹400 per team (4 members)',
    prizes: 'Prize Pool: ₹20,000',
    date: 'March 5th, 2026',
    timing: '9:00 AM - 02:00 PM',
    duration: '5 Hours',
    venue: 'Nano labs',
    contactName: 'P. Akhil Charan Kumar',
    contactDetails: '7670850910',
    facultyCoordinator: 'Dr. P V S Anusha',
    facultyContact: '9502616962',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLScCyGsSnys8x-Bj4YDUbzlZrAWXP84pvZRsR4cqgv18nLdjsw/viewform',
  },
  {
    title: 'LEVEL UP',
    club: 'GDG OnCampus REC',
    description: 'LevelUp is an engaging and competitive tech event designed to test participants’ problem-solving, creativity, and teamwork skills through exciting rounds of challenges',
    longDescription: 'LevelUp is a multi-round technical and fun-based competition aimed at creating an exciting platform for students to showcase their skills, collaborate with peers, and enhance their problem-solving abilities. The event blends technology, creativity, and teamwork through a series of engaging challenges that progressively increase in difficulty — truly reflecting the spirit of leveling up. Participants will face diverse rounds that may include coding challenges, logical reasoning, technical quizzes, creative activities, and team-based tasks. Each round is designed to evaluate different skill sets such as analytical thinking, innovation, communication, and adaptability under pressure. Beyond competition, LevelUp promotes learning, networking, and experiential growth. It provides a space where students can explore their potential, gain exposure to real-world problem solving, and enjoy a thrilling competitive atmosphere. Whether you are a tech enthusiast, creative thinker, or strategic problem solver, LevelUp is the perfect opportunity to challenge yourself, have fun, and take your skills to the next level',
    fees: '1-4 members',
    prizes: 'TBD',
    date: 'March 7th, 2026',
    timing: '9:00 AM - 12:30 PM',
    duration: '3 hours 30 minutes',
    venue: 'Nano labs - 1,2',
    contactName: 'Harsha',
    contactDetails: '8897485396',
    facultyCoordinator: 'P. Narasimharaju',
    facultyContact: '6301923220',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLScSzOYJU3KjhqM1vSy0NKS7nhZ7mlQ2u_eFKiq8EuEltDoi9w/formResponse?pli=1',
  },
  {
    title: 'TECH IN BORDERLAND',
    club: 'GFG',
    description: 'The event consists of four progressive rounds, each mapped to a card suit: Diamonds(Intelligence), Clubs (Teamwork), Spades (Speed & Physical Coordination), and Hearts(Psychology & Decision-Making).',
    longDescription: '→TECH IN BORDERLAND is a multi-round technical competition inspired by card-based challenges, designed to test participants across intelligence, teamwork, speed, physical coordination, and decision-making skills.',
    fees: '₹120/- ',
    prizes: '₹3000/- TO ₹4000/-',
    date: 'March 7th, 2026',
    timing: '9:30 AM to 12:30 PM',
    duration: '3 Hours',
    venue: 'C block Lab 9,10 & 3,4',
    contactName: 'B Sehwag Ganesh',
    contactDetails: '8143407814',
    facultyCoordinator: 'P Sowjanya',
    facultyContact: '',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfWxvYRHYUGzDZcBJGIvdTHy6ulC7O3ALFtqOOw5SS05QxY-A/viewform'
  },
  {
    title: 'TECH ASTRA',
    club: 'RAIC',
    description: 'It is a flagship gamified technical championship organized by RAIC – Raghu Artificial Intelligence Club during Chakravuyh 2K26. ',
    longDescription: 'This is a team-based technical competition (2 members per team) where participants rotate through five distinct technical stations known as the Five Astras: Shabda-Astra – Technical quiz testing precision and accuracy in core technical knowledge. Vayu-Astra – Rapid AI idea design challenge assessing innovation and structured thinking. Brahma-Astra – AI tools knowledge test combined with strategic problem-solving. Agney-Astra – Coding and debugging challenge evaluating technical execution and focus. Maya-Astra – AI-based creative editing task assessing visual transformation skills.',
    fees: 'Individual - ₹50/- & DUO - ₹80 /-',
    prizes: 'TBD',
    date: 'March 7th, 2026',
    timing: '9:30 AM - 12:30 PM',
    duration: '3 hours 30minutes',
    venue: 'SF60 LAB IN C-BLOCK',
    contactName: 'S. Vidya Sagar',
    contactDetails: '7671921576',
    facultyCoordinator: 'G.Balakrishna',
    facultyContact: '9177420430',
    category: 'technical',
    registrationLink: 'https://forms.gle/rBuQ45hDJYKnvBaC6'
  },
  {
    title: 'DATA PARADOX',
    club: 'DATA SCIENCE DEPARTMENT',
    description: 'The Prediction Auction is a dynamic data-driven competition where participants analyze real-world datasets, predict outcomes, and strategically',
    longDescription: 'Participants are provided with real-world datasets such as sales trends, placements data, performance statistics, or similar structured information. Teams must carefully analyze the data, identify patterns, observe trends, and predict the next possible value based on logical reasoning and numerical insights.',
    fees: '₹149 per Team 2-4',
    prizes: '₹3000/-',
    date: 'March 6th, 2026',
    timing: '9 AM to 1 PM',
    duration: '4 Hours',
    venue: 'NANO LABS',
    contactName: 'K.Abhishek',
    contactDetails: '8309114596',
    facultyCoordinator: 'P. Advitya Siva Shankar',
    facultyContact: '9705655102',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSejGqwEn_HHuHqsMD9Lle_GajUvoSEqRTsr3Md6sdCiMQNIiw/viewform'
  },
  {
    title: 'ESCAPE ROOM',
    club: 'Raghu Scope',
    description: 'The Sequential Team Escape Challenge (Internet-Based) is an interactive online puzzle competition where teams solve a series of challenges in a fixed order. ',
    longDescription: 'In this event, participants compete in teams. Each team progresses through multiple levels of challenges in a fixed sequence. A new level unlocks only after the previous level is correctly completed, ensuring structured progression and fair competition.',
    fees: '₹150 per team 3-4',
    prizes: 'upto ₹2000',
    date: 'March 7th, 2026',
    timing: '9:00AM to 12:00AM',
    duration: '4 Hours',
    venue: 'Lab 1,2 - CSM Block',
    contactName: 'CH VARSHINI',
    contactDetails: '7981080369',
    facultyCoordinator: 'Dr. PVS Anusha',
    facultyContact: '',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSekXQgJqBMSR1bWj8N82i--zYUJ02xeysE1s9Fy9AOSKuPjng/viewform?usp=header',
  },
  {
    title: 'BLIND TOUCH',
    club: 'Mechanical Department',
    description: 'Blind Touch"is an engineering workshop event where participants are blindfolded and challenged to assemble or repair a mechanical component using only their sense of touch.',
    longDescription: 'Blind Touch is a fun and interactive technical event where participants are blindfolded and asked to identify mechanical tools and components using only their sense of touch. This event tests practical knowledge, sensory skills, confidence, and presence of mind. Participants must correctly name the tools within the given time limit.',
    fees: '₹30 per head',
    prizes: 'TBD',
    date: 'March 4th & 5th, 2026',
    timing: 'starts at 10 am',
    duration: 'Clashing time will be revealed during',
    venue: 'Engineering WorkShop Beside subhash Chandrabose block',
    contactName: 'S.komali',
    contactDetails: '8121147363',
    facultyCoordinator: 'M.Teja Srikanth',
    facultyContact: '9505662608',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdIqPVEZ9CAqb6dLF3r4HJOPu1Fcv3eV8VUgeYw3g5xZlEVkg/viewform',
  },
  {
    title: 'CAD CLASH',
    club: 'Mechanical Department',
    description: 'CAD CLASH is a technical drafting competition designed to test participants’ visualization skills, projection knowledge, and drafting accuracy using AutoCAD.',
    longDescription: 'Round 1: Orthographic to Isometric – Participants convert 2D Orthographic views into complete Isometric views using AutoCAD. Round 2: Isometric to Orthographic – Participants generate proper Front, Top, and Side views from given Isometric drawings.',
    fees: '₹50',
    prizes: 'upto ₹1000',
    date: 'March 7th, 2026',
    timing: 'starts at 10 am',
    duration: 'Clashing time will be revealed during the event.',
    venue: 'Nano Block (cad cam lab)',
    contactName: 'Vivek Anuroop',
    contactDetails: '9398644081',
    facultyCoordinator: 'S. Sanyasi Rao',
    facultyContact: '9703116696',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfmQDGHyNaGKxmYW8YM0yZvVIovlPyZDSj_2dOhD0HtcJrhKg/viewform',
  },
  {
    title: 'CIRCUIT DIGEST',
    club: 'EEE DEPARTMENT',
    description: 'CIRCUIT DIGEST is a multi-round technical event designed to test participants’ knowledge of electrical and electronic components, memory skills, and practical circuit-building abilities.',
    longDescription: 'Round 1 – Component Matching: Participants will match electrical components such as resistors, capacitors, diodes, transistors, LEDs, etc., with their correct names. Round 2 – Memory Test: Several electrical and electronic components will be displayed on a screen for a limited time. Participants must write down as many component names as they remember. Round 3 – LED Glowing Challenge: Participants will be provided with required electrical components. Initially, 4 LEDs will be given. They must connect the circuit and glow the maximum number of LEDs correctly. The participant/team that glows the highest number of LEDs will be declared the winner.',
    fees: 'Solo: ₹50 rupees, Team: ₹100 rupees only 3 members',
    prizes: 'Upto ₹1000 rupees',
    date: 'March 3rd, 2026',
    timing: 'TBD',
    duration: '5 Hours',
    venue: 'Ground floor classroom, Swami Vivekanadha block',
    contactName: 'BANUJA PARIDA',
    contactDetails: '8074330425',
    facultyCoordinator: 'D. NARENDRA',
    facultyContact: '9110317091',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSe7gK73SYFdIS9dPW5GNpUPAj1oN-5EFrNvhJqL0RwabPTr_A/viewform',
  },
  {
    title: 'Circuitry Connect',
    club: 'SPARKS',
    description: 'This competition consists of three dynamic rounds designed to test participants’ technical knowledge, speed, strategy, and practical electronics skills',
    longDescription: 'In Round 1, titled The Virtual Junkyard, teams participate in a fast-paced visual scavenger hunt where they must quickly identify electronic hardware components from a projected image within a 10-minute time limit, testing their observation and recognition abilities. In Round 2, participants are provided with either a circuit diagram or a pre-assembled circuit and are required to identify the type of circuit and demonstrate their understanding of its function and purpose. In the final round, the Auction-Based Circuit Connection Round, teams are given a problem statement to design a specific electronic circuit, but instead of receiving components directly, they must strategically bid for them using virtual currency earned from their performance in the previous rounds. After successfully acquiring components, they must assemble the circuit neatly, use only the purchased components, ensure proper functionality, and clearly explain the working of their designed circuit. Overall, the event evaluates technical expertise, problem-solving ability, teamwork, time management, and strategic decision-making',
    fees: '',
    prizes: '',
    date: 'March 4th, 2026',
    timing: ' 9am to 4pm',
    duration: 'Full Day',
    venue: 'BEEE Lab, ECE Department, Subash Chandra Bose Block',
    contactName: 'MD Vaseem Ahmed',
    contactDetails: '7993788988',
    facultyCoordinator: 'Dr. A. Vamsidhar',
    facultyContact: '9849332767',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdCNZWkH9RRALNuy9NAubh58iwg0RURQIWLRTQ_Qsfo_FUqxQ/viewform',
  },
  {
    title: 'ELECTRO MYSTERY',
    club: 'SPARKS',
    description: 'This electrifying competition consists of four dynamic rounds designed to strengthen the understanding of ECE fundamentals',
    longDescription: 'enhance problem-solving skills among students. In Round 1, titled Sherlock Ohms (Treasure Hunt), teams participate in a fun, interactive activity where they must solve technical clues and logic puzzles. They must solve the given puzzle to find next clue where it is located and goes on for a specified time and the eligible teams will be qualified for Round 2. In Round 2, Component Chronicles, participants are challenged to accurately identify various electronic components and symbols. Round 3, Scholar Sprint (Paper Decode), focuses on technical comprehension, where participants must answer technical questions derived from provided IEEE papers. In the final round, the Spark Showdown (Technical Quiz),',
    fees: 'solo: 60/- & team (max 3): 150/-',
    prizes: 'TBD',
    date: 'March 4th, 2026',
    timing: '9:00 AM to 4:00 PM',
    duration: 'Full Day',
    venue: 'DSP Lab, Swami Vivekananda Block, ECE Department',
    contactName: 'KOTTANA CREESHMA',
    contactDetails: '9121759667',
    facultyCoordinator: 'Dr. A VAMSIDHAR',
    facultyContact: '9849332767',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeJ7rX0JTxxtsuqHhTgL0-uGih8jowL4TnSOAVFdnAgl2yNpg/viewform',
  },
  {
    title: 'Idea Volt',
    club: 'SPARKS',
    description: 'Idea Volt is a technical poster presentation event that encourages students to explore and present emerging technologies and current technical issues.',
    longDescription: 'Idea Volt is designed to ignite innovation and technical thinking among students by providing a platform to showcase knowledge on trending and futuristic technologies. Participants can choose from five domains — Quantum Computing, Green Internet, Molecular Nanotechnology, Underwater Communications, and Satellites — and prepare a concise one-page poster highlighting key concepts, applications, challenges, and future scope.',
    fees: 'solo: 60/- & duo: 100/-',
    prizes: 'TBD',
    date: 'March 5th, 2026',
    timing: '1 pm to 4 pm',
    duration: '3 Hours',
    venue: 'Swami Vivekananda Block, 1st Floor',
    contactName: 'J.MADHUMITHA',
    contactDetails: '8309748077',
    facultyCoordinator: 'Dr.M.S.S.S.SRlNlVAS',
    facultyContact: '9849672252',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdxfEphawbt8EQWkZla6LOpibBon2qZDOYjw0hLZp6Pg5KAag/viewform',
  },
  {
    title: 'JAM SESSION',
    club: 'EEE DEPARTMENT',
    description: 'JAM (Just A Minute) Session is a fun and interactive event designed to test participants communication skills, confidence, spontaneity, and presence of mind. Participants must speak on a given topic for one minute without hesitation, repetition, or deviation.',
    longDescription: 'Participants will be evaluated based on: Clarity of thought, Technical knowledge, Communication skills, Confidence and fluency Ability to avoid hesitation, repetition, or deviation',
    fees: 'solo: ₹50 per participant',
    prizes: 'TBD',
    date: 'March 4th, 2026',
    timing: 'TBD',
    duration: '2–3 Hours',
    venue: 'SWAMI VIVEKANANDA BLOCK GROUND FLOOR',
    contactName: 'V.ANUSHKA',
    contactDetails: '8074467424',
    facultyCoordinator: 'D. NARENDRA',
    facultyContact: '9110317091',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSevDcF5qZDebTy0hHkn5A8L7lMr8_AG2a5qnyYYoCg6MB7Atg/viewform',
  },
  {
    title: 'POSTER PRESENTATION',
    club: 'EEE DEPARTMENT',
    description: 'PosterPresentation is a technical event that provides students a platform to present innovative ideas, research concepts, and emerging technologies in the field of Electrical and Electronics Engineering. ',
    longDescription: 'Poster Presentation: Duration: 8–10 minutes presentation + 2–3 minutes Q&A. Judging Criteria: Technical Content,Innovation and Originality,Presentation Skills,Clarity and Confidence,Ability to Answer',
    fees: 'solo – 50/- & team – 100/- for 3 ',
    prizes: 'upto 1000/-',
    date: 'March 4th, 2026',
    timing: 'TBD',
    duration: '3-4 Hours',
    venue: 'Ground floor classroom, Swami Vivekanadha block',
    contactName: 'S. NANDINI',
    contactDetails: '7396334137',
    facultyCoordinator: 'D. NARENDRA',
    facultyContact: '9110317091',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSc74xhbv-Yr3mBfvpcOpv9slek89oY7YlTqp1XQ0tEpzxVNNw/viewform',
  },
  {
    title: 'QUIZ FORGE',
    club: 'CIVIL DEPARTMENT',
    description: 'The Technical Quiz is a knowledge-based competition organized to test students understanding of technical subjects and current trends in technology. It provides a platform for participants to showcase their skills, improve confidence, and engage in healthy academic competition.',
    longDescription: 'Quiz Forge is a technical quiz event organized to encourage students to strengthen their subject knowledge and stay updated with advancements in technology. The competition is open to students from all departments who are interested in testing their technical understanding in a structured and competitive environment.',
    fees: '',
    prizes: '',
    date: 'March 4th 2026',
    timing: '10:00 AM – 12:00 PM',
    duration: '2 Hours',
    venue: 'CIVIL 3rd year classroom in BGT-block',
    contactName: 'R. Yogesh',
    contactDetails: '6281997263',
    facultyCoordinator: 'Dr. I. Krishna Chaitanya',
    facultyContact: '9701750007',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdcZT22oC2xvaSu5HU0rLITgyuIxP4vTF2vFeUopttJsVpEQw/viewform?us',
  },
  {
    title: 'TOWER OF BALANCE',
    club: 'CIVIL DEPARTMENT',
    description: 'Tower of Balance is a fun and challenging team activity that tests coordination, patience, and strategic thinking. Participants must carefully stack objects to build the tallest and most stable tower within the given time limit.',
    longDescription: 'Tower of Balance is an interactive team-based event designed to enhance focus, teamwork, and problem-solving skills. In this activity, each team must construct the tallest possible tower using the materials provided (such as playing cards or other stacking items) within the allotted time.',
    fees: '',
    prizes: '',
    date: 'March 5th, 2026',
    timing: '1:00 PM - 3:00 PM',
    duration: '2 Hours',
    venue: 'LAB 1,2 - CSM BLOCK',
    contactName: 'V. Sree Teja',
    contactDetails: '9059813949',
    facultyCoordinator: 'Dr. G. Vincent Jasmine',
    facultyContact: '8106669180',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdGcw_wF2bfkiq14I7TudTOj4P_UtzgZkVWsWTDkXd_AnYetg/viewform',
  },
  {
    title: 'MONOPOLY-X',
    club: ' E Cell REC',
    description: 'MONOPOLY X is a live, high-energy startup economy simulation where teams compete as founders in a fast-moving market.',
    longDescription: 'MONOPOLY X is a live, high-energy startup economy simulation where teams compete as founders in a fast-moving market. Players use strategy, negotiation, and risk-taking to acquire assets, form deals, survive market shocks, and grow their business empires within a fixed time. With power cards, live auctions, and crowd-driven dynamics, the game transforms a fest into an immersive, competitive experience focused on finance, decision-making, and market psychology',
    fees: '',
    prizes: '',
    date: 'March 7th, 2026',
    timing: '10:00 AM to 12:30 PM',
    duration: '120 min - 150 min',
    venue: 'Incubator centre',
    contactName: 'Venkatnadh',
    contactDetails: '9059882468',
    facultyCoordinator: '',
    facultyContact: '',
    category: 'technical',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSeW-TuxceMwdlo4puVzrz8Wxw4_JCbEetf2sfaXE4WwlCtDzA/viewform',
  },
  // ================== Non-Technical Events ==================
  

  // ================== Special Events ==================
  {
    title: 'Moto Expo',
    club: 'Special Event',
    description: 'Where 900+ CC Beasts Assemble.',
    longDescription: 'Witness a lineup of superbikes that redefine speed, power, and engineering dominance. Feel the vibration of roaring engines and the raw adrenaline in the air. Get up close with machines built for 300+ km/h performance and fearless riders. This isn’t just an exhibition — it’s a celebration of pure horsepower and attitude. 🏍️🔥',
    date: 'March 7th, 2026',
    timing: '10:00 AM - 03:00 PM',
    duration: '5 Hours',
    venue: 'Central Quadrangle',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'DJ Night',
    club: 'Special Event',
    description: 'Where the Campus Loses Control.',
    longDescription: 'When the lights drop and the bass hits, there’s no standing still. Feel the music take over as beats, lights, and energy collide in one explosive night. Dance like nobody’s watching, scream like you own the moment. This isn’t just a party — it’s the night Chakravyuh turns into pure madness',
    date: 'March 8th, 2026',
    timing: '06:00 PM onwards',
    duration: '4 Hours',
    venue: 'Open Grounds',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Live Band Night',
    club: 'Special Event',
    description: 'Where Music Takes Over the Stage.',
    longDescription: 'Feel the drums thunder, the guitars ignite, and the vocals send chills through the crowd. Every beat hits harder, every chorus louder, every moment unforgettable. Sing at the top of your lungs as the stage turns into pure electric energy. This isn’t just a performance — it’s a night where music owns the campus. 🎸🔥',
    date: 'March 7th, 2026',
    timing: '07:00 PM onwards',
    duration: '3 Hours',
    venue: 'Main Stage',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Fireworks',
    club: 'Special Event',
    description: 'The Sky Will Not Stay Silent.',
    longDescription: 'As the night falls, the darkness shatters into explosions of color and light. Every spark ignites the sky, every burst echoes celebration and chaos. Look up as the campus transforms into a canvas of fire and brilliance. This isn’t just a display — it’s the grand finale that leaves everyone breathless. 🎆🔥',
    date: 'March 8th, 2026',
    timing: '08:30 PM',
    duration: '15 Minutes',
    venue: 'Main Gate Sky',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Stand-Up Comedy',
    club: 'Special Event',
    description: 'Laughter You Can’t Escape.',
    longDescription: 'When the mic turns on, no one is safe — not departments, not professors, not even you. Every punchline hits harder than a surprise test, every joke sharper than reality. From awkward campus moments to brutal truths, everything becomes comedy gold. This isn’t just a show — it’s a time where stress disappears and laughter takes control. 🎤🔥',
    date: 'March 8th, 2026',
    timing: '04:00 PM - 06:00 PM',
    duration: '2 Hours',
    venue: 'Auditorium',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Miss & Mr. Raghu',
    club: 'Special Event',
    description: 'Where Legends Rise.',
    longDescription: 'Confidence meets charisma as the spotlight searches for the true faces of Raghu. It’s not just about style — it’s about attitude, intelligence, and undeniable presence. Every walk, every answer, every second on stage could change everything. This isn’t a title — it’s a crown earned under pressure.',
    date: 'March 8th, 2026',
    timing: '02:00 PM - 04:00 PM',
    duration: '2 Hours',
    venue: 'Main Stage',
    category: 'special-events',
    registrationLink: '#',
  },
];
