
export interface Event {
  title: string;
  club: string;
  description: string;
  longDescription: string;
  registrationLink?: string;
  eventType?: string;
  targetAudience?: string;
  participants?: string;
  duration?: string;
  venue?: string;
  fees?: string;
  prizes?: string;
  requirements?: {
    technical?: string[];
    resources?: string[];
    special?: string;
  };
  volunteers?: string;
  contactName?: string;
  contactDetails?: string;
  facultyCoordinator?: string;
  facultyContact?: string;
  category: 'technical' | 'non-technical' | 'special-events';
}

export const eventsData: Event[] = [
  // ================== Technical Events ==================
  {
    title: 'Project Expo',
    club: 'Raghu Scope',
    description: 'An open-domain project showcase for innovations in IoT, AI, robotics, and more. Teams of up to 4 members.',
    longDescription: 'The Project Expo is an open-domain platform for students to showcase their innovative projects in fields like IoT, AI, robotics, software applications, and more. A great opportunity to get feedback and recognition for your hard work.',
    fees: '₹400 per team (4 members)',
    prizes: 'Prize Pool: ₹20,000',
    contactName: 'P. Akhil Charan Kumar',
    contactDetails: '7670850910',
    facultyCoordinator: 'Dr. P V S Anusha',
    facultyContact: '9502616962',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Component & Circuit Challenge',
    club: 'IEEE Society',
    description: 'A multi-round challenge testing your knowledge of electronic components and circuits, culminating in an auction-based design round.',
    longDescription: 'Round 1 involves the identification of various electronic components. Round 2 challenges participants to identify complete circuits. The final round is a competitive, auction-based circuit design challenge where teams bid for components to build a functional circuit.',
    fees: '₹50 (Individual), ₹90 (2 members), ₹120 (3 members)',
    prizes: "based upon registrations",
    requirements: {
      resources: ['Room (150+ capacity)', 'WiFi router', '2 mics', '1 speaker', 'Electronic components', 'A4 sheets', 'Projector'],
    },
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'TECH IN BORDERLAND',
    club: 'GFG',
    description: 'A multi-round technical competition inspired by card-based challenges, testing intelligence, teamwork, speed, and psychology.',
    longDescription: 'A multi-round technical competition inspired by card-based challenges. Rounds are mapped to suits: Diamonds (Intelligence), Clubs (Teamwork), Spades (Speed & Coordination), Hearts (Psychology & Decision Making). The final round includes a difficulty card selection (Jack/Queen/King/Joker) and an offline quiz.',
    fees: '₹120 per team',
    prizes: 'Based on registrations',
    contactName: 'B Sehwag Ganesh',
    contactDetails: '9346827882',
    requirements: {
      resources: ['2 Labs', 'Projector', 'WiFi', 'Power supply', 'Decoration (~₹1000)', '2–3 mics & speakers'],
    },
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'DATA PARADOX - The Prediction Auction',
    club: 'Data Science Department',
    description: 'Data Paradox — The Prediction Auction is a strategic data analysis',
    longDescription: 'Data Paradox is a strategic data analysis challenge. Participants are provided with real-world datasets and must analyze patterns, identify trends, and predict the next value. Teams use virtual coins to invest based on their confidence. Accurate predictions earn profits, while incorrect ones result in losses. The team with the most coins wins.',
    fees: 'For Online - 99/-  &  For Spot Registration -79/-',
    prizes: 'Top - 1 : 1000/- & Top -2 : 500/-',
    contactName: 'Kolagani Abishek',
    contactDetails: '8309114596',
    facultyCoordinator: 'Pyla Adithya Siva Shankar',
    facultyContact: '9705655102',
    requirements: {
      resources: ['Mic set', 'Projector', 'Refreshments (Samosa, Fruity)', 'Participation Certificates', 'Swags'],
    },
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'GAMEVERSE',
    club: 'Raghu Artificial Intelligence Club (RAIC)',
    description: 'GameVerse Tech Challenge is a gamified technical event where participants rotate across 5 different game stations.',
    longDescription: 'GameVerse Tech Challenge is a gamified technical event where participants rotate across 5 different game stations, each testing a different skill set in a fun, competitive environment.',
    fees: 'Team of 1 - ₹30, Team of 2 - ₹50',
    prizes: '₹3000 - ₹4000',
    venue: 'Hall / Computer Lab',
    contactName: 'G. Balakrishna',
    contactDetails: '9177426430',
    facultyCoordinator: 'Dr. S. Vidya Sagar',
    facultyContact: '+91 76719 21578',
    requirements: {
      technical: ['Mics/Speakers','Projector / Screen', 'Internet / Wi-Fi', 'Power Supply & Extension Cables'],
      resources: ['Tables, Chairs', 'budget for hall decoration in range of 700/- to 1100/-', 'carrom board for one station from sports department'],
    },
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Circulink',
    club: 'IETE',
    description: 'It consists of four rounds like 1.virtual treasuer hunt,2.quiz,3.Guess the output?3.Build it if u can?',
    longDescription: 'Circulink consists of four exciting rounds: 1. Virtual Treasure Hunt, 2. Quiz, 3. Guess the Output, 4. Build it if you can. Test your skills across a variety of technical domains.',
    fees: '₹50 (Single), ₹80 (Duo), ₹120 (Three)',
    prizes: 'Based on registrations',
    contactName: 'P. Ganapathi',
    contactDetails: '6300856587',
    facultyCoordinator: 'Dr. M.S.S.S. Srinivas',
    facultyContact: '9849672252',
    requirements: {
        resources: ['rit seminar hall', '100 capacity class room', 'full wifi', 'ece lab', 'ece equipment like-ardunio boards,sensors etc...'],
    },
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Improvement of Resume Skills',
    club: 'IETE',
    description: 'Developing the personal development(like as a workshop)',
    longDescription: 'This workshop focuses on developing personal and professional skills, guiding participants on how to build an effective and impactful resume to stand out to recruiters.',
    fees: '₹30',
    prizes: 'Based on registrations',
    contactName: 'P. Ganapathi',
    contactDetails: '6300856587',
    facultyCoordinator: 'Dr. M.S.S.S. Srinivas',
    facultyContact: '9849672252',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Poster Presentation',
    club: 'EEE Department',
    description: 'Present your technical concepts and projects. Judged on concept, presentation, and depth of knowledge.',
    longDescription: 'A platform for students to showcase their technical projects and ideas through poster presentations. Participants will be judged on the clarity of their concept, the quality of their presentation, and their depth of understanding.',
    fees: '₹50 (Solo), ₹100 (Group)',
    prizes: 'Based on registrations',
    facultyCoordinator: 'D. Narendra',
    facultyContact: '9110317091',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'JAM',
    club: 'EEE Department',
    description: 'A 1-minute technical speaking challenge. Test your knowledge and communication skills under pressure.',
    longDescription: 'Participants are given a technical topic and must speak on it for one minute without hesitation, repetition, or deviation. This event tests technical knowledge, quick thinking, and public speaking skills.',
    fees: '₹50',
    prizes: 'Based on registrations',
    facultyCoordinator: 'D. Narendra',
    facultyContact: '9110317091',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Level Up',
    club: 'Google Developer Groups on Campus REC',
    description: 'A gamified multi-round event where participants complete challenges to gain experience points and level up.',
    longDescription: 'Level Up is a gamified multi-round event where participants complete various technical challenges to gain experience points (XP). The participant with the highest XP at the end wins.',
    fees: '₹100 per person',
    prizes: 'Prize Pool: ₹15,000',
    contactName: 'Thanush',
    contactDetails: '7989710860',
    facultyCoordinator: 'P Narsimharaju',
    facultyContact: '6301923220',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Cloud Quest',
    club: 'AWS Cloud Clubs',
    description: 'A gamified cloud learning challenge designed to test your skills on the AWS platform.',
    longDescription: 'Cloud Quest is a gamified learning challenge that helps participants build practical cloud skills through interactive labs and challenges on the AWS platform.',
    fees: '₹30',
    prizes: 'Based on registrations',
    contactName: 'T.V. Sathwik Sai',
    contactDetails: '7989524511',
    facultyCoordinator: 'Shivkumar',
    facultyContact: '9885993418',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'QuizForge',
    club: 'Civil Engineering Department',
    description: 'A technical quiz testing core knowledge in civil engineering concepts and practices.',
    longDescription: 'QuizForge is a technical quiz designed to test participants\' deep understanding of core civil engineering principles, from structural analysis to modern construction materials.',
    fees: '₹50',
    prizes: 'Based on registrations',
    contactName: 'Meesala Chandu',
    contactDetails: '9701337291',
    facultyCoordinator: 'Shiva',
    facultyContact: '8106866235',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Toryu Challenge (Tower of Balance)',
    club: 'Civil Engineering Department',
    description: 'Build the tallest, most stable structure using a limited set of materials. A test of engineering and creativity.',
    longDescription: 'The Toryu Challenge, or Tower of Balance, tasks teams with building the tallest and most stable structure possible using only a limited set of provided materials. It\'s a battle of creativity, structural integrity, and resource management.',
    fees: '₹50 (Solo), ₹80 (2 members)',
    prizes: 'Based on registrations',
    contactName: 'Meesala Chandu',
    contactDetails: '9701337291',
    facultyCoordinator: 'Shiva',
    facultyContact: '8106866235',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Escape Room',
    club: 'Raghu Scope',
    description: 'A thrilling, puzzle-based team challenge. Can you and your team solve the clues and escape in time?',
    longDescription: 'A themed, immersive experience where teams must work together to find clues, solve a series of complex puzzles, and complete a mission to "escape" the room within a set time limit.',
    fees: '₹50 per head',
    prizes: 'Prize Pool: ₹2000',
    contactName: 'P. Akhil Charan Kumar',
    contactDetails: '7670850910',
    facultyCoordinator: 'Dr. P V S Anusha',
    facultyContact: '9502616962',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'CAD Clash',
    club: 'Mechanical Department',
    description: 'A multi-round CAD challenge designed to test your design and modeling skills to the limit.',
    longDescription: 'CAD Clash is a multi-round competition for CAD enthusiasts. Participants will face a series of design and modeling challenges with increasing difficulty, testing their speed, accuracy, and creativity.',
    fees: '₹50',
    prizes: '₹1000',
    contactName: 'S. Manoj Kumar',
    contactDetails: '8688765915',
    facultyCoordinator: 'M. Teja Srikanth',
    facultyContact: '9505662608',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Guess the Component',
    club: 'Mechanical Department',
    description: 'A fun challenge where participants are blindfolded and must identify mechanical components by touch.',
    longDescription: 'A unique sensory challenge where participants are blindfolded and must use their sense of touch to identify various mechanical components. Tests your practical knowledge and familiarity with parts.',
    fees: '₹50',
    prizes: '₹1000',
    contactName: 'S. Manoj Kumar',
    contactDetails: '8688765915',
    facultyCoordinator: 'M. Teja Srikanth',
    facultyContact: '9505662608',
    category: 'technical',
    registrationLink: '#',
  },
  {
    title: 'Queens Arena',
    club: 'FEMSPIRE CLUB',
    description: 'A multi-round team coding competition for girls, including MCQs, jumbled code, debugging, and blind coding.',
    longDescription: 'Queens Arena is a team-based coding competition exclusively for girls. The event consists of multiple challenging rounds: Multiple Choice Questions, Jumbled Code, Debugging, and the ultimate test—Blind Coding.',
    fees: '₹150 per team',
    prizes: 'Medals & Certificates',
    contactName: 'K. Pavani / M. Harshini',
    contactDetails: '8309623653 / 8074040041',
    facultyCoordinator: 'D. Nagamani',
    facultyContact: '8985916833',
    category: 'technical',
    registrationLink: '#',
  },

  // ================== Non-Technical Events ==================
  {
    title: 'MONOPOLY',
    club: 'E-Cell REC',
    description: 'A high-stakes startup and market simulation where teams build, trade, and dominate under time pressure.',
    longDescription: 'This is not your average board game. MONOPOLY at Chakravyuh is a high-intensity startup simulation. Teams of 3 must make quick decisions, negotiate deals, and manage resources in a competitive environment to build their empire.',
    fees: '₹180 (Team of 3)',
    prizes: '₹3000',
    contactName: 'E Sri Ram Vishal',
    contactDetails: '9490147819',
    facultyCoordinator: 'G Kiran Kumar',
    facultyContact: '9154971659',
    category: 'non-technical',
    registrationLink: '#',
  },
  {
    title: 'IPL Auction',
    club: 'E-Cell REC',
    description: 'A simulated IPL auction where teams act as franchises, bidding for players to create the ultimate team.',
    longDescription: 'Experience the thrill of the Indian Premier League auction! Form a franchise team and strategically bid for your favorite players to assemble a championship-winning squad. Tests your strategic thinking, financial management, and cricketing knowledge.',
    fees: '₹180 (Team of 3)',
    prizes: '₹3500',
    contactName: 'E Sri Ram Vishal',
    contactDetails: '9490147819',
    facultyCoordinator: 'G Kiran Kumar',
    facultyContact: '9154971659',
    category: 'non-technical',
    registrationLink: '#',
  },
  {
    title: 'Movie Quiz',
    club: 'Chitraalaya Club',
    description: 'A multi-round, competitive trivia about movies.',
    longDescription: 'Movie quiz is a multi-round, competitive trivia. Moving beyond simple Q&A, this event features diverse rounds such as Identify the Soundtrack (audio cues), The Pixelated Poster (visual puzzles), and Dialogue Mashups.',
    eventType: 'Competition',
    targetAudience: 'Open to all',
    participants: '100+',
    duration: '2-3 hrs',
    venue: 'lab/ seminar hall',
    requirements: {
      technical: ['Projector / Screen', 'Sound System / Mic', 'Internet / Wi-Fi', 'Power Supply'],
      resources: ['supplies for decorations'],
    },
    volunteers: '30 (for decorations)',
    contactName: 'SHAIK AZIM REHAN',
    contactDetails: '7095235557',
    category: 'non-technical',
    registrationLink: '#',
  },
  {
    title: 'Cine Quest',
    club: 'Chitraalaya Club',
    description: 'An immersive, campus-wide scavenger hunt with a film crew theme.',
    longDescription: 'Cine-Quest is an immersive, campus-wide scavenger hunt that puts participants in the shoes of a film crew racing against a "production deadline." Instead of traditional clues, teams are given "Call Sheets" containing movie-themed riddles, iconic dialogue ciphers, and plot-based puzzles. To move from one station to the next, teams must complete "On-Set Challenges"',
    eventType: 'Competition',
    targetAudience: 'Open to all',
    participants: '30+',
    duration: '2 hrs',
    venue: '4-5 open locations',
    requirements: {
      technical: ['Projector / Screen', 'Sound System / Mic', 'Internet / Wi-Fi', 'Power Supply'],
      resources: ['supplies for decorations'],
    },
    volunteers: '30 (for decorations)',
    contactName: 'SHAIK AZIM REHAN',
    contactDetails: '7095235557',
    category: 'non-technical',
    registrationLink: '#',
  },
  {
    title: 'Caricature Stall',
    club: 'Akruthi Fine Arts Club',
    description: 'Live caricature sketches of students, faculty, and visitors.',
    longDescription: 'A Live Caricature Stall will be set up where skilled artists from the club will create quick caricature sketches of students, faculty, and visitors. This interactive stall will be a major attraction, encouraging engagement, fun, and memorable takeaways for the attendees.',
    eventType: 'Live Art Stall',
    targetAudience: 'Open to all',
    participants: '150–250 visitors',
    duration: '9:00 am to 4:00 pm',
    venue: 'Dedicated stall space',
    requirements: {
      technical: ['Sound System / Mic', 'Power Supply / Extension Cables'],
      resources: ['Art supplies (sketch papers, markers, pencils, frames)', 'Tables, chairs, easels, and display stands'],
    },
    volunteers: '20-30',
    contactName: 'A.V.S.Nrupesh',
    contactDetails: '9989542961',
    category: 'non-technical',
    registrationLink: '#',
  },
  {
    title: 'Art Expo',
    club: 'Akruthi Fine Arts Club',
    description: 'An exhibition of student artworks.',
    longDescription: 'An art expo where our student artists will showcase their artworks, including paintings, sketches, illustrations, crafts, miniatures, and mixed-media works. This expo will serve as a platform for students to display their creativity, gain exposure, and interact with visitors.',
    eventType: 'Art Exhibition',
    targetAudience: 'Open to all',
    duration: '9:00 am to 4:00 pm',
    venue: 'Exhibition Area',
    requirements: {
      resources: ['Display stands, tables, chairs'],
    },
    volunteers: '20-30',
    contactName: 'A.V.S.Nrupesh',
    contactDetails: '9989542961',
    category: 'non-technical',
    registrationLink: '#',
  },
  {
    title: 'Band Performance',
    club: 'Saptaswara Music Club',
    description: 'A live band performance by the student music club.',
    longDescription: 'Saptaswara Music Club proposes to present a live band performance. The band will perform a curated set of songs across genres such as classical fusion, semi-classical, and contemporary music, ensuring the content is appropriate, meaningful, and engaging for a diverse audience.',
    eventType: 'Performance',
    targetAudience: 'Open to all',
    participants: 'Club members only (around 10)',
    duration: '2 hr',
    venue: 'Open Area',
    requirements: {
      technical: ['Screen', 'Sound Systems, Mic, Instruments', 'Power Supply', 'Lighting'],
    },
    contactName: 'Khyathi',
    contactDetails: '7013727543',
    category: 'non-technical',
    registrationLink: '#',
  },

  // ================== Special Events ==================
  {
    title: 'Moto Expo',
    club: 'Special Event',
    description: 'Where 900+ CC Beasts Assemble. Witness a lineup of superbikes that redefine speed, power, and engineering dominance.',
    longDescription: 'Witness a lineup of superbikes that redefine speed, power, and engineering dominance. Feel the vibration of roaring engines and the raw adrenaline in the air. Get up close with machines built for 300+ km/h performance and fearless riders. This isn’t just an exhibition — it’s a celebration of pure horsepower and attitude. 🏍️🔥',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'DJ Night',
    club: 'Special Event',
    description: 'Where the Campus Loses Control. When the lights drop and the bass hits, there’s no standing still.',
    longDescription: 'When the lights drop and the bass hits, there’s no standing still. Feel the music take over as beats, lights, and energy collide in one explosive night. Dance like nobody’s watching, scream like you own the moment. This isn’t just a party — it’s the night Chakravyuh turns into pure madness',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Live Band Night',
    club: 'Special Event',
    description: 'Where Music Takes Over the Stage. Feel the drums thunder, the guitars ignite, and the vocals send chills through the crowd.',
    longDescription: 'Feel the drums thunder, the guitars ignite, and the vocals send chills through the crowd. Every beat hits harder, every chorus louder, every moment unforgettable. Sing at the top of your lungs as the stage turns into pure electric energy. This isn’t just a performance — it’s a night where music owns the campus. 🎸🔥',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Fireworks',
    club: 'Special Event',
    description: 'The Sky Will Not Stay Silent. As the night falls, the darkness shatters into explosions of color and light.',
    longDescription: 'As the night falls, the darkness shatters into explosions of color and light. Every spark ignites the sky, every burst echoes celebration and chaos. Look up as the campus transforms into a canvas of fire and brilliance. This isn’t just a display — it’s the grand finale that leaves everyone breathless. 🎆🔥',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Stand-Up Comedy',
    club: 'Special Event',
    description: 'Laughter You Can’t Escape. When the mic turns on, no one is safe.',
    longDescription: 'When the mic turns on, no one is safe — not departments, not professors, not even you. Every punchline hits harder than a surprise test, every joke sharper than reality. From awkward campus moments to brutal truths, everything becomes comedy gold. This isn’t just a show — it’s a time where stress disappears and laughter takes control. 🎤🔥',
    category: 'special-events',
    registrationLink: '#',
  },
  {
    title: 'Miss & Mr. Raghu',
    club: 'Special Event',
    description: 'Where Legends Rise. Confidence meets charisma as the spotlight searches for the true faces of Raghu.',
    longDescription: 'Confidence meets charisma as the spotlight searches for the true faces of Raghu. It’s not just about style — it’s about attitude, intelligence, and undeniable presence. Every walk, every answer, every second on stage could change everything. This isn’t a title — it’s a crown earned under pressure.',
    category: 'special-events',
    registrationLink: '#',
  },
];
