
export interface Event {
  title: string;
  club: string;
  description: string;
  longDescription: string;
  eventType?: string;
  targetAudience?: string;
  participants?: string;
  duration?: string;
  venue?: string;
  fees?: string;
  prizes?: string;
  requirements?: {
    technical?: string[];
    resources?: string[];
    special?: string;
  };
  volunteers?: string;
  contactName?: string;
  contactDetails?: string;
  facultyCoordinator?: string;
  facultyContact?: string;
  category: 'technical' | 'non-technical' | 'sports';
}

export const eventsData: Event[] = [
  // DATA SCIENCE DEPARTMENT
  {
    title: 'DATA PARADOX - THE PREDICTION AUCTION',
    club: 'Data Science Department',
    description: 'A strategic data analysis challenge where you predict trends and auction on your confidence.',
    longDescription: 'Data Paradox — The Prediction Auction is a strategic data analysis challenge conducted as part of Chakravyuh 2K26 by the Data Science Department, Raghu Engineering College. In this event, participants are provided with real-world datasets and must analyze patterns, identify trends, and predict the next value. Teams are given virtual coins and must decide how much to invest based on their confidence in their prediction. Accurate predictions earn profits, while incorrect predictions result in losses, making the event a blend of data analytics, logical thinking, and risk management. The team with the highest number of virtual coins at the end of all rounds will be declared the winner.',
    fees: 'Online: ₹99 | Spot Registration: ₹79',
    prizes: 'Top 1: ₹1000 | Top 2: ₹500',
    category: 'technical',
    eventType: 'Competition',
    targetAudience: 'Open to all',
    requirements: {
      resources: ['Mic set', 'Projector', 'Refreshments(Samosa , Fruity)', 'Participation Certificates', 'Swags'],
    },
    contactName: 'KOLAGANI ABISHEK',
    contactDetails: '8309114596',
    facultyCoordinator: 'PYLA ADITHYA SIVA SHANKAR',
    facultyContact: '9705655102',
  },
  // E-CELL REC CLUB
  {
    title: 'MONOPOLY X – Build. Trade. Dominate.',
    club: 'E-Cell REC',
    description: 'A high-intensity, real-world startup and market simulation.',
    longDescription: 'MONOPOLY X is a high-intensity, real-world startup and market simulation designed as a flagship anchor event for the Techfest. Participants act as startup founders competing in a live, multiplayer economy where they bid for assets, negotiate deals, form alliances, manage risks, and respond to sudden market events. This is not a board game but a dynamic economic battlefield where decisions are public, time-bound, and consequential.',
    eventType: 'Flagship Competition / Live Economic Simulation',
    targetAudience: 'Open to all (Engineering, Management, Startup & Finance enthusiasts)',
    participants: '120–150 participants (Teams of 3)',
    duration: '2.5 – 3 hours',
    venue: 'Large Hall / Indoor Stadium / Open Area',
    requirements: {
      technical: ['Projector / LED Screen', 'Sound System & Wireless Mic', 'Stable Internet / Wi-Fi', 'Power Supply & Extension Cables'],
      resources: ['Tables & chairs for teams', 'Printed asset cards, power cards, and currency tokens', 'Whiteboards / Standee boards for zones', 'Central banking desk setup'],
    },
    volunteers: '15–20',
    contactName: 'E Sri Ram Vishal',
    contactDetails: '9490147819',
    facultyCoordinator: 'Dr G. Kiran Kumar (IIC Convenor, Physics HOD)',
    facultyContact: '+91 99496 51218',
    category: 'non-technical',
  },
  {
    title: 'Startup Expo – Techfest Vizag',
    club: 'E-Cell REC',
    description: 'An exhibition and networking event for regional startups.',
    longDescription: 'The Startup Expo is designed to bring together real, early-stage and growth-stage startups from the Vizag startup ecosystem under one roof. It serves as a convergence point for innovation, entrepreneurship, students, mentors, and industry professionals. Startups will showcase their products, technologies, and business models through dedicated stalls.',
    eventType: 'Exhibition / Networking Event',
    targetAudience: 'Open to all (Students, Founders, Industry Professionals)',
    participants: '1,000+ visitors; 15–20 startups',
    duration: 'Full Day / Multi-hour Expo Window',
    venue: 'Open Hall / Exhibition Area',
    requirements: {
      technical: ['Power supply for stalls', 'Internet / Wi-Fi', 'Optional screens for demos', 'Canopy Setups'],
      resources: ['Exhibition stalls/ Canopy (15–20)', 'Tables, chairs', 'Category signage and navigation layout'],
    },
    volunteers: '8–12',
    contactName: 'E Sri Ram Vishal',
    contactDetails: '9490147819',
    facultyCoordinator: 'Dr G. Kiran Kumar (IIC Convenor, Physics HOD)',
    facultyContact: '+91 99496 51218',
    category: 'non-technical',
  },
  {
    title: 'Entrepreneur Talk Shows',
    club: 'E-Cell REC',
    description: 'Interactive talk shows with celebrity entrepreneurs and founders.',
    longDescription: 'The Entrepreneur Talk Shows are interactive, moderated sessions featuring celebrity entrepreneurs and influencer founders. Unlike traditional keynote speeches, these sessions follow a talk-show format with conversation-driven discussions, real-world stories, and audience interaction. The focus is on practical insights, failures, pivots, and real startup journeys rather than scripted monologues.',
    eventType: 'Tech Talk / Interactive Talk Show',
    targetAudience: 'Open to all',
    participants: '200–500 per session',
    duration: '60–90 minutes per session',
    venue: 'Auditorium / Seminar Hall',
    requirements: {
        technical: ['Projector / LED Screen', 'Sound System & Wireless Mics', 'Recording setup (optional)'],
        resources: ['Stage seating (Guest + Moderator)', 'Branding backdrop', 'Audience seating arrangement'],
    },
    volunteers: '6–8',
    contactName: 'E Sri Ram Vishal',
    contactDetails: '9490147819',
    facultyCoordinator: 'Dr G. Kiran Kumar (IIC Convenor, Physics HOD)',
    facultyContact: '+91 99496 51218',
    category: 'non-technical',
  },
  // GDG CLUB
  {
      title: 'Level Up',
      club: 'GDGonCampus REC',
      description: 'A gamified tech experience blending creativity, problem-solving, and communication.',
      longDescription: 'This event is a gamified tech experience designed to break away from traditional hackathons and coding contests. Instead of focusing only on programming, it brings together creativity, problem-solving, communication, and real-world tech thinking in an engaging and fun format. Participants will face a series of interactive challenges, role-based tasks, puzzles, and scenario-driven rounds inspired by real technology problems and the digital world around us. The event encourages collaboration, quick thinking, and innovation—making it accessible and exciting for students from all branches, regardless of their technical background. With live interactions, audience engagement, and dynamic tasks, the event aims to create a festival-like atmosphere where learning feels like play and technology feels relatable, inclusive, and impactful.',
      eventType: 'Competition',
      targetAudience: 'Open to all',
      participants: '200',
      duration: '4 Hrs',
      venue: 'Hall / Classroom / Lab / Open Area',
      requirements: {
          technical: ['Projector / Screen', 'Internet / Wi-Fi', 'Power Supply / Extension Cables'],
          resources: ['Tables', 'Chairs'],
      },
      volunteers: '30',
      contactName: 'C V Thanush',
      contactDetails: '7989710860',
      category: 'technical',
  },
  {
      title: 'Tech Model United Nations',
      club: 'GDGonCampus REC',
      description: 'An immersive UN simulation to solve global challenges with technology.',
      longDescription: 'Tech Model United Nations (TMUN), organised by Google Developer Groups (GDG), is an immersive simulation of the United Nations designed to explore how technology can be leveraged to address global challenges. The event brings together students to represent different countries and engage in structured diplomatic discussions while proposing technology-driven solutions aligned with the United Nations Sustainable Development Goals (SDGs). Participants will assume the roles of UN delegates and take part in moderated and unmoderated debates, resolution drafting, crisis simulations, and voting procedures that closely follow official UN protocols. Unlike traditional Model United Nations conferences, TMUN integrates modern technological perspectives such as artificial intelligence, cybersecurity, data analytics, and digital governance into policy formulation and decision-making.',
      eventType: 'Competition',
      targetAudience: 'Open to all',
      participants: '150',
      duration: '2-4 Hrs',
      venue: 'Hall / Classroom / Lab / Open Area',
      requirements: {
          technical: ['Projector / Screen', 'Sound System / Mic', 'Internet / Wi-Fi', 'Power Supply / Extension Cables'],
          resources: ['United Nations delegates setup (Tables, chairs, systems)'],
      },
      volunteers: '10',
      contactName: 'C V Thanush',
      contactDetails: '7989710860',
      category: 'non-technical',
  },
  // RAIC CLUB
  {
      title: 'AIcon – Edit the Future',
      club: 'RAIC Club',
      description: 'A hands-on, AI-driven creative editing event blending creativity and technology.',
      longDescription: 'AIcon – Edit the Future is a hands-on, AI-driven creative editing event aimed at exposing students to modern content creation workflows powered by artificial intelligence. The event blends creativity, technology, and industry practices through multiple competitive rounds and an expert-led workshop. Participants will work in teams to design posters, generate AI-assisted videos, and perform professional-level editing using a mix of AI tools and manual techniques. Each round progressively challenges participants’ design sense, storytelling ability, AI tool usage, and professional editing skills.',
      eventType: 'Competition + Workshop',
      targetAudience: 'Open to all',
      participants: '150',
      duration: '6 Hours (10:00 AM – 4:00 PM)',
      venue: 'Hall / Classroom',
      requirements: {
          technical: ['Projector / Screen', 'Sound System / Microphone', 'Internet / Wi-Fi', 'Power Supply / Extension Cables'],
          resources: ['Tables', 'Chairs', 'Participant Systems (Laptops/Desktops)'],
      },
      contactName: 'G.Bala Krishna',
      contactDetails: '9177426430',
      category: 'technical',
  },
  {
    title: 'GAMEVERSE',
    club: 'Raghu Artificial Intelligence Club (RAIC)',
    description: 'A gamified tech event where participants rotate across 5 different game stations.',
    longDescription: 'GameVerse Tech Challenge is a gamified technical event where participants rotate across 5 different game stations.',
    fees: 'Team of 2: ₹50 | Team of 1: ₹30',
    prizes: '₹3000 - ₹4000',
    venue: 'Hall / Computer Lab',
    requirements: {
        technical: ['Mics/Speakers', 'Projector/Screen', 'Internet/Wi-Fi', 'Power Supply & Extension Cables'],
        resources: ['Tables', 'Chairs', 'Hall decoration budget: ₹700-₹1100', 'Carrom board'],
    },
    contactName: 'G.BALAKRISHNA',
    contactDetails: '9177426430',
    facultyCoordinator: 'Dr.S.Vidya Sagar',
    facultyContact: '+91 76719 21578',
    category: 'technical',
  },
  // IETE CLUB
  {
    title: 'Circulink',
    club: 'IETE',
    description: 'A multi-round technical challenge including a virtual treasure hunt, quiz, and hardware building.',
    longDescription: 'Circulink is a multi-round technical event designed to test a variety of skills. It consists of four exciting rounds: a virtual treasure hunt, a technical quiz, a "Guess the Output" challenge, and a hands-on "Build it if you can" round.',
    fees: 'Based on registrations',
    prizes: 'Based on registrations',
    category: 'technical',
    eventType: 'Competition',
    requirements: {
      resources: ['RIT seminar hall', '100 capacity classroom', 'Full WiFi', 'ECE lab', 'Arduino boards, sensors, etc.'],
    },
    contactName: 'P.GANAPATHI',
    contactDetails: '6300856587',
    facultyCoordinator: 'Dr. M.S.S.S.S.Srinivas',
    facultyContact: '98496 72252',
  },
  {
    title: 'Improvement of Resume Skills',
    club: 'IETE',
    description: 'A workshop focused on developing personal and resume-building skills.',
    longDescription: 'This workshop is focused on personal development and is designed to help participants improve their resume-building skills. It will cover key aspects of crafting a professional resume that stands out.',
    fees: '₹30',
    prizes: 'Based on registrations',
    category: 'technical',
    eventType: 'Workshop',
    requirements: {
      resources: ['RIT seminar hall', '100 capacity classroom', 'Full WiFi'],
    },
    contactName: 'P.GANAPATHI',
    contactDetails: '6300856587',
    facultyCoordinator: 'Dr. M.S.S.S.S.Srinivas',
    facultyContact: '98496 72252',
  },
  // CHITRALAYA ClUB
  {
    title: 'Movie Quiz',
    club: 'Chitraalaya Club',
    description: 'A multi-round, competitive trivia about movies.',
    longDescription: 'Movie quiz is a multi-round, competitive trivia. Moving beyond simple Q&A, this event features diverse rounds such as Identify the Soundtrack (audio cues), The Pixelated Poster (visual puzzles), and Dialogue Mashups.',
    eventType: 'Competition',
    targetAudience: 'Open to all',
    participants: '100+',
    duration: '2-3 hrs',
    venue: 'lab/ seminar hall',
    requirements: {
      technical: ['Projector / Screen', 'Sound System / Mic', 'Internet / Wi-Fi', 'Power Supply'],
      resources: ['supplies for decorations'],
    },
    volunteers: '30 (for decorations)',
    contactName: 'SHAIK AZIM REHAN',
    contactDetails: '7095235557',
    category: 'non-technical',
  },
  {
    title: 'Cine Quest',
    club: 'Chitraalaya Club',
    description: 'An immersive, campus-wide scavenger hunt with a film crew theme.',
    longDescription: 'Cine-Quest is an immersive, campus-wide scavenger hunt that puts participants in the shoes of a film crew racing against a "production deadline." Instead of traditional clues, teams are given "Call Sheets" containing movie-themed riddles, iconic dialogue ciphers, and plot-based puzzles. To move from one station to the next, teams must complete "On-Set Challenges"',
    eventType: 'Competition',
    targetAudience: 'Open to all',
    participants: '30+',
    duration: '2 hrs',
    venue: '4-5 open locations',
    requirements: {
      technical: ['Projector / Screen', 'Sound System / Mic', 'Internet / Wi-Fi', 'Power Supply'],
      resources: ['supplies for decorations'],
    },
    volunteers: '30 (for decorations)',
    contactName: 'SHAIK AZIM REHAN',
    contactDetails: '7095235557',
    category: 'non-technical',
  },
  // AKRUTHI ARTS CLUB
  {
    title: 'Caricature Stall',
    club: 'Akruthi Fine Arts Club',
    description: 'Live caricature sketches of students, faculty, and visitors.',
    longDescription: 'A Live Caricature Stall will be set up where skilled artists from the club will create quick caricature sketches of students, faculty, and visitors. This interactive stall will be a major attraction, encouraging engagement, fun, and memorable takeaways for the attendees.',
    eventType: 'Live Art Stall',
    targetAudience: 'Open to all',
    participants: '150–250 visitors',
    duration: '9:00 am to 4:00 pm',
    venue: 'Dedicated stall space',
    requirements: {
      technical: ['Sound System / Mic', 'Power Supply / Extension Cables'],
      resources: ['Art supplies (sketch papers, markers, pencils, frames)', 'Tables, chairs, easels, and display stands'],
    },
    volunteers: '20-30',
    contactName: 'A.V.S.Nrupesh',
    contactDetails: '9989542961',
    category: 'non-technical',
  },
  {
    title: 'Art Expo',
    club: 'Akruthi Fine Arts Club',
    description: 'An exhibition of student artworks.',
    longDescription: 'An art expo where our student artists will showcase their artworks, including paintings, sketches, illustrations, crafts, miniatures, and mixed-media works. This expo will serve as a platform for students to display their creativity, gain exposure, and interact with visitors.',
    eventType: 'Art Exhibition',
    targetAudience: 'Open to all',
    duration: '9:00 am to 4:00 pm',
    venue: 'Exhibition Area',
    requirements: {
      resources: ['Display stands, tables, chairs'],
    },
    volunteers: '20-30',
    contactName: 'A.V.S.Nrupesh',
    contactDetails: '9989542961',
    category: 'non-technical',
  },
  // FEMSPIRE CLUB
  {
    title: 'Queen’s Arena',
    club: 'FemSpire Club',
    description: 'A strength, stamina, and teamwork-based event for girls.',
    longDescription: 'Queen’s Arena is a strength, stamina, and teamwork-based event that combines physical and mental challenges, conducted in a station-based format. This event aims to prove that girls are physically strong, mentally sharp, and excellent team players.',
    eventType: 'Competition',
    targetAudience: 'All branches (Girls only)',
    participants: '150–200 (combined)',
    duration: '3 to 4 hours',
    venue: 'One open area / hall',
    requirements: {
      resources: ['Cups, ropes, bottles, basic props'],
    },
    volunteers: '10-15',
    contactName: 'Miriyala Harshini',
    contactDetails: '8074040041',
    category: 'sports',
  },
  {
    title: 'Mind Maze',
    club: 'FemSpire Club',
    description: 'A mental ability and presence-of-mind competition for girls.',
    longDescription: 'Mind Maze is a mental ability and presence-of-mind competition designed to test participants’ logical thinking, memory power, observation skills, and decision-making ability under pressure. It consists of multiple rounds including logic, memory, and situational decision-making.',
    eventType: 'Competition',
    targetAudience: 'All branches (Girls only)',
    duration: '3 to 4 hours',
    venue: 'Classrooms',
    requirements: {
      technical: ['Projector and screen', 'Sound system and microphone'],
      resources: ['Question papers (MCQs, puzzles)', 'Pens, papers, charts'],
    },
    volunteers: '10-15',
    contactName: 'Miriyala Harshini',
    contactDetails: '8074040041',
    category: 'non-technical',
  },
  {
      title: 'Tech Relay',
      club: 'FemSpire Club',
      description: 'A fast-paced, team-based technical competition in a relay format.',
      longDescription: 'Tech Relay is a fast-paced, team-based technical competition conducted in a relay format. Each team consists of four members, and each member participates in one round: a technical quiz round, a debugging round, a logic puzzle round, and a problem explanation round. The team progresses step-by-step like a relay race. This event emphasizes teamwork, basic technical knowledge, problem-solving skills, and the ability to explain ideas clearly in a simple and practical manner.',
      eventType: 'Competition',
      targetAudience: 'All branches (Girls only)',
      venue: 'Classrooms',
      requirements: {
          technical: ['Projector and screen', 'Sound system and microphone', '2-3 laptops (optional)'],
          resources: ['Question papers (MCQs, puzzles, debugging sheets)', 'Pens, papers, charts', 'Stopwatch / Timer'],
      },
      volunteers: '10–15',
      contactName: 'Miriyala Harshini',
      contactDetails: '8074040041',
      category: 'technical',
  },
  // IOT CLUB
  {
      title: 'Project Expo 2025',
      club: 'Raghu Scope - IoT club',
      description: 'A platform for students to showcase their innovative ideas and technical projects.',
      longDescription: 'The Project Expo 2025 aims to provide a platform for students to showcase their innovative ideas and technical projects. Participants will present working models or project concepts based on real-world problems across domains such as IoT, software, automation, and sustainable technology. This event encourages hands-on learning, creativity, and technical presentation skills, making it highly relevant for a TechFest by promoting innovation and practical application of knowledge.',
      eventType: 'Competition / Exhibition',
      targetAudience: 'Open to all branches and all years from all Colleges',
      participants: '100+ students',
      duration: 'One-day event | 9:00 AM – 4:00 PM',
      venue: 'Seminar Hall / Large Classroom / Open Hall',
      requirements: {
          technical: ['Projector / Screen', 'Sound System / Microphone', 'Internet / Wi-Fi (optional)', 'Power Supply & Extension Cables'],
          resources: ['Tables for project display', 'Chairs for participants and judges', 'Display boards/charts', 'Writing materials'],
      },
      volunteers: '3',
      contactName: 'K. Sandeep',
      contactDetails: '7670996681',
      category: 'technical',
  },
  // SAPTASWARA MUSIC CLUB
  {
    title: 'Band Performance',
    club: 'Saptaswara Music Club',
    description: 'A live band performance by the student music club.',
    longDescription: 'Saptaswara Music Club proposes to present a live band performance. The band will perform a curated set of songs across genres such as classical fusion, semi-classical, and contemporary music, ensuring the content is appropriate, meaningful, and engaging for a diverse audience.',
    eventType: 'Performance',
    targetAudience: 'Open to all',
    participants: 'Club members only (around 10)',
    duration: '2 hr',
    venue: 'Open Area',
    requirements: {
      technical: ['Screen', 'Sound Systems, Mic, Instruments', 'Power Supply', 'Lighting'],
    },
    contactName: 'Khyathi',
    contactDetails: '7013727543',
    category: 'non-technical',
  },
  // CREATIVE HUB
  {
      title: 'Designathon',
      club: 'Creative Hub',
      description: 'A focused, time-bound competition integrating design thinking with practical innovation.',
      longDescription: 'The Designathon is a focused, time-bound competition where teams will integrate design thinking with practical innovation. The central challenge—a real-world problem statement—will be revealed at the start of the event. The core objective is for participants to conceptualize and deliver comprehensive design solutions. The emphasis is on design thinking, creativity, user experience (UX), and feasibility, not coding. Teams will be tasked with creating interfaces, branding assets, and functional prototypes to address the problem.',
      eventType: 'Design & Innovation Competition',
      targetAudience: 'Open to all students (All Branches & Years)',
      participants: '~100 participants',
      duration: '6-7 Hours',
      venue: 'Seminar Hall / Design Lab / Classrooms',
      requirements: {
          technical: ['Projector', 'Internet Access', 'Power Supply'],
          resources: ['Tables and seating for participating teams and judges'],
      },
      contactName: 'Ch Teja, Jyothish',
      contactDetails: '7207884991, 7396979306',
      category: 'technical',
  },
  // SPORTS SECTION
  {
    title: 'Cricket',
    club: 'Sports Committee',
    description: 'Inter-branch cricket tournament.',
    longDescription: 'A classic knockout cricket tournament to find the champion team of the campus. Bring your team and compete for glory.',
    eventType: 'Sports Competition',
    targetAudience: 'Open to all',
    category: 'sports',
  },
  {
    title: 'Basketball',
    club: 'Sports Committee',
    description: '3-on-3 basketball challenge.',
    longDescription: 'Fast-paced 3-on-3 basketball tournament. Form your trio and showcase your skills on the court.',
    eventType: 'Sports Competition',
    targetAudience: 'Open to all',
    category: 'sports',
  },
  {
    title: 'Volleyball',
    club: 'Sports Committee',
    description: 'Classic volleyball tournament.',
    longDescription: 'Feel the heat with our volleyball tournament. Teams will compete in a league followed by knockouts.',
    eventType: 'Sports Competition',
    targetAudience: 'Open to all',
    category: 'sports',
  },
  {
    title: 'Tennis',
    club: 'Sports Committee',
    description: 'Singles and doubles tennis tournament.',
    longDescription: 'Aces, volleys, and smashes. Compete in our singles and doubles tennis tournament to be crowned the champion.',
    eventType: 'Sports Competition',
    targetAudience: 'Open to all',
    category: 'sports',
  },
];
