export const testimonials = [
  {
    quote: "As the Overall Chairperson of Chakravyuh Fest 2025 I demonstrated exceptional leadership and organizational skills. My ability to coordinate multiple teams, handle challenges calmly, and ensure smooth execution of events played a crucial role in the success of the fest.",
    name: "K.Raghavendra",
    role: "Chairperson",
    imageUrl: "/testimonials/exchair.jpeg",
  },
  {
    quote: "The core team organized a successful event, overcoming challenges while ensuring enjoyment. As the head of sponsorship, I acknowledge the vital support of my team and staff, expressing hope for the event to become an annual tradition.",
    name: "Nithin Narayana",
    role: "Sponsors head",
    imageUrl: "/testimonials/NithinNarayana.jpeg",
  },
  {
    quote: "As the Sponsorship and Accounts lead for Chakravyuh Fest 2025, I played a key role in securing sponsors and managing finances efficiently. My professional approach and clear communication ensured smooth collaboration with partners and accurate handling of budgets.",
    name: "Reddy Harsha Vardhan",
    role: "Accounts and sponsor",
    imageUrl: "/testimonials/harsha.jpeg",
  },
  {
    quote: "As the Resource Management Head for Chakravyuh, I am proud of the scale and excellence our team achieved. From overseeing event infrastructure, branding, décor, certification workflows, and end-to-end logistics to ensuring seamless participant services, we transformed meticulous planning into flawless execution.",
    name: "Ravindranadh",
    role: "Cyber security",
    imageUrl: "testimonials/Ravindranadh.jpeg",
  },
  {
    quote: "As a Core Team Member – Resource Management, what began as a simple idea slowly turned into a beautiful reality. Playing a major role in the entire college decoration for Chakravyuh 2K25, I witnessed firsthand the effort, pressure, and passion behind every detail that brought the campus to life.",
    name: "Ruttala Yaswanth",
    role: "Resource Management",
    imageUrl: "/testimonials/RuttalaYaswanth.jpeg",
  },
    {
    quote: "A fest like Chakravyuh is more than just an event, it’s an identity. As Media Cell Head, I worked with a dedicated team to ensure this fest was felt everywhere. We collaborated with every club, pushed fellow students to create, and built the hype frame by frame.",
    name: "Ch. Dhaneshwar",
    role: "Media Cell Head",
    imageUrl: "/testimonials/unnamed.jpeg",
  },
  {
    quote: "As the Treasurer(Accountant) of the Chakravyuh 2K25, I take pride in the effective financial planning and execution that supported the smooth conduct of the fest. With the cooperation and trust of the entire team, resources were managed responsibly to ensure the success of all events.",
    name: "S.Giri Charan Naidu",
    role: "Treasurer",
    imageUrl: "/testimonials/GiriCharanNaidu.jpeg",
  },
  {
    quote: "As the Technical Events Head of Chakravyuh 2K25, I feel proud to have contributed to the planning and successful execution of the fest’s technical events. With the constant support, coordination, and enthusiasm of the team, we were able to organize engaging and innovative events that encouraged learning, creativity, and participation among students. Being part of Chakravyuh 2K25 has been a valuable experience, and I hope this fest continues to grow as a flagship annual event of Raghu Engineering College.",
    name: "M. Ojaswani",
    role: "Technical Events Head",
    imageUrl: "/testimonials/Ojaswani.jpeg",
  },
  {
    quote: "As the cheif security head of the chakravyuh 2k25, I lead the team of 100 with the perfect planning and guidance. With the cooperation of the team and trust of entire team was the reason for the success of all events. I hope the team of fest 2k26 continue the legacy and tradition with grace and guidance. All the best team. Rock it.",
    name: "Niharikaa",
    role: "cheif security head",
    imageUrl: "/testimonials/Niharikaa.jpeg",
  },
  {
    quote: "As a Non technical head ,What started as an idea had now become a remarkable success. Conducting NON-TECH EVENTS under Chakravyuh 2K25 was possible only because of the collective effort, coordination, and commitment of each one of us. With thousands of participants and the smooth execution of every event, we didn’t just organize a fest—we created an experience. This success stands as proof of our teamwork, planning, and dedication. Proud to have led such an energetic and responsible team.",
    name: "G.MOULI SRIMUKESH",
    role: "Non Technical Head",
    imageUrl: "/testimonials/mouli.jpeg",
  },
  {
    quote: "As a Core Team Member and Media Cell Head for Chakravyuh 2K25, this journey meant more to me than just creating posters and promo videos. Every design, every edit, and every update carried my passion, emotions, and dedication. There were sleepless nights, pressure, and endless efforts behind every piece of content. But seeing students connect with our work and feel the excitement of the fest made everything worth it. This experience taught me that media is not just about visuals it is about creating emotions and memories that stay forever. Proud and grateful to be part of this beautiful journey.",
    name: "Kalyan Koushik",
    role: "Media Cell Head",
    imageUrl: "/testimonials/kalyan.jpeg",
  },
  {
    quote: "As the Stalls Person, I worked hard to ensure everything went smoothly, and it paid off. Thanks to the team and attendees for making it a blast.",
    name: "T. Purna Siva Sai Manikanta",
    role: "Stalls Head",
    imageUrl: "/testimonials/Manikanta.jpeg",
  },
  {
    quote: "As Tech Lead for Chakravyuh Fest 2025, I'm stoked to have led the tech team to make the event a hit. The team's hard work and my expertise came together to create an unforgettable tech extravaganza.",
    name: "N raghavendra",
    role: "Tech Lead",
    imageUrl: "/testimonials/Raghavendra.jpeg",
  },
];
